#ifndef SERRON_COMPAT_REGISTRATION_H
#define SERRON_COMPAT_REGISTRATION_H

// Compatibility shim for the local CMake / PyPI build.

#include <torch/library.h>

#define TORCH_LIBRARY_EXPAND(NAME, MODULE) TORCH_LIBRARY(NAME, MODULE)

#define TORCH_LIBRARY_IMPL_EXPAND(NAME, DEVICE, MODULE) TORCH_LIBRARY_IMPL(NAME, DEVICE, MODULE)

#define TORCH_EXTENSION_NAME serron

#define REGISTER_EXTENSION(NAME)

#endif // SERRON_COMPAT_REGISTRATION_H