"""
Op-namespace loader for the local CMake / PyPI build.
"""

from __future__ import annotations

import glob
import importlib
import os
import sys
from typing import Protocol, cast

import torch

_NAMESPACE = "serron"


def _search_dirs() -> list[str]:
    dirs = [os.path.dirname(__file__)]
    pkg = sys.modules.get(_NAMESPACE)
    if pkg is not None:
        dirs.extend(getattr(pkg, "__path__", ()))
    return list(dict.fromkeys(dirs))


def _find_library(stem: str) -> str | None:
    for pkg_dir in _search_dirs():
        for pattern in (f"{stem}.*so", f"{stem}.*pyd", f"{stem}.*dll"):
            matches = glob.glob(os.path.join(pkg_dir, pattern))
            if matches:
                return matches[0]
    return None


def _release(version: str) -> tuple[int, ...]:
    """``(major, minor, micro)`` of ``version``, ignoring any local or pre-release suffix."""
    head = version.split("+")[0]
    parts: list[int] = []
    for part in head.split(".")[:3]:
        digits = "".join(c for c in part if c.isdigit())
        if not digits:
            break
        parts.append(int(digits))
    return tuple(parts)


class _BuildInfo(Protocol):
    TORCH_TARGET_VERSION: str
    TORCH_VERSION: str
    STABLE_ABI: bool


def _build_info() -> _BuildInfo | None:
    # Generated by CMake, so absent when running from a bare source tree.
    try:
        return cast("_BuildInfo", importlib.import_module(f"{__package__}._build_info"))
    except ImportError:
        return None


def _load(path: str) -> None:
    info = _build_info()
    built_for = info.TORCH_VERSION if info is not None else None
    try:
        torch.ops.load_library(path)
    except OSError as exc:
        raise ImportError(
            f"Could not load the compiled Serron extension {os.path.basename(path)} "
            f"(built against torch {built_for or 'unknown'}, installed torch is {torch.__version__}): {exc}"
        ) from exc


def _check_torch_version() -> None:
    """
    Reject a torch too old for this build.

    Built against the stable ABI, the extension loads on its target version and every later one, so the bound is
    one-sided. Without it the extension is tied to the exact minor it was compiled against, because the torch C++
    ABI changes between minor releases.
    """
    info = _build_info()
    if info is None:
        return

    if not info.STABLE_ABI:
        if _release(info.TORCH_VERSION)[:2] != _release(torch.__version__)[:2]:
            raise ImportError(
                f"Serron was built against torch {info.TORCH_VERSION}, but torch {torch.__version__} is "
                f"installed, and this build does not target the stable ABI. The torch C++ ABI changes between "
                f"minor releases: install a matching torch, or rebuild Serron against the installed one."
            )
        return

    target = info.TORCH_TARGET_VERSION
    if _release(torch.__version__) < _release(target):
        raise ImportError(
            f"Serron needs torch {target} or newer, but torch {torch.__version__} is installed. "
            f"Upgrade torch, or rebuild Serron from source against the installed version."
        )


def _load_c_extension() -> None:
    _check_torch_version()

    cpu_lib = _find_library("_C")
    if cpu_lib is None:
        raise ImportError(
            f"Could not find the compiled Serron '_C' extension in {_search_dirs()}. Reinstall the package so the kernels are built."
        )
    _load(cpu_lib)

    cuda_lib = _find_library("_C_cuda")
    if cuda_lib is not None and torch.version.cuda is not None:
        _load(cuda_lib)


# autocast per device type
_AUTOCAST_DTYPES = {"cuda": torch.float16, "cpu": torch.bfloat16}

# FWD -> takes path, BWD -> gets from fwd
_AUTOCAST_OPS = ("erode", "dilate")


def _register_autocast() -> None:
    """
    Make the operators participate in ``torch.autocast``.

    The stable ABI has no equivalent of ``at::autocast``, so the ops are registered with the dispatcher instead.
    """
    for device_type, dtype in _AUTOCAST_DTYPES.items():
        for op in _AUTOCAST_OPS:
            torch.library.register_autocast(f"{_NAMESPACE}::{op}", device_type, dtype)


_load_c_extension()
_register_autocast()

ops = getattr(torch.ops, _NAMESPACE)


def add_op_namespace_prefix(op_name: str) -> str:
    return f"{_NAMESPACE}::{op_name}"
