"""
Op-namespace loader for the local CMake / PyPI build.
"""

from __future__ import annotations

import glob
import importlib
import os
import sys

import torch

_NAMESPACE = "serron"


def _search_dirs() -> list[str]:
    dirs = [os.path.dirname(__file__)]
    pkg = sys.modules.get(_NAMESPACE)
    if pkg is not None:
        dirs.extend(getattr(pkg, "__path__", ()))
    return list(dict.fromkeys(dirs))


def _find_library(stem: str) -> str | None:
    for pkg_dir in _search_dirs():
        for pattern in (f"{stem}.*so", f"{stem}.*pyd", f"{stem}.*dll"):
            matches = glob.glob(os.path.join(pkg_dir, pattern))
            if matches:
                return matches[0]
    return None


def _minor(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("+")[0].split(".")[:2])


def _build_torch_version() -> str | None:
    # Generated by CMake, so absent when running from a bare source tree.
    try:
        build_info = importlib.import_module(f"{__package__}._build_info")
    except ImportError:
        return None
    version: str = build_info.TORCH_VERSION
    return version


def _load(path: str) -> None:
    built_for = _build_torch_version()
    try:
        torch.ops.load_library(path)
    except OSError as exc:
        raise ImportError(
            f"Could not load the compiled Serron extension {os.path.basename(path)} "
            f"(built against torch {built_for or 'unknown'}, installed torch is {torch.__version__}): {exc}"
        ) from exc


def _load_c_extension() -> None:
    built_for = _build_torch_version()
    if built_for is not None and _minor(built_for) != _minor(torch.__version__):
        raise ImportError(
            f"Serron was built against torch {built_for}, but torch {torch.__version__} is installed. "
            f"The torch C++ ABI changes between minor releases: install torch "
            f"{'.'.join(map(str, _minor(built_for)))}.x, or rebuild Serron from source against the installed torch."
        )

    cpu_lib = _find_library("_C")
    if cpu_lib is None:
        raise ImportError(
            f"Could not find the compiled Serron '_C' extension in {_search_dirs()}. Reinstall the package so the kernels are built."
        )
    _load(cpu_lib)

    cuda_lib = _find_library("_C_cuda")
    if cuda_lib is not None and torch.version.cuda is not None:
        _load(cuda_lib)


# autocast per device type
_AUTOCAST_DTYPES = {"cuda": torch.float16, "cpu": torch.bfloat16}

# FWD -> takes path, BWD -> gets from fwd
_AUTOCAST_OPS = ("erode", "dilate")


def _register_autocast() -> None:
    """
    Make the operators participate in ``torch.autocast``.

    The stable ABI has no equivalent of ``at::autocast``, so the ops are registered with the dispatcher instead.
    """
    for device_type, dtype in _AUTOCAST_DTYPES.items():
        for op in _AUTOCAST_OPS:
            torch.library.register_autocast(f"{_NAMESPACE}::{op}", device_type, dtype)


_load_c_extension()
_register_autocast()

ops = getattr(torch.ops, _NAMESPACE)


def add_op_namespace_prefix(op_name: str) -> str:
    return f"{_NAMESPACE}::{op_name}"
